/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */

export interface AdminDtoAlbum {
  created_at?: number;
  id?: string;
  participant_count?: number;
  title?: string;
  total_cards?: number;
}
