/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */
import type { AdminDtoAlbum } from './adminDtoAlbum';
import type { AdminDtoUser } from './adminDtoUser';
import type { CardModelCard } from './cardModelCard';

export interface AdminDtoUserDetail {
  albums?: AdminDtoAlbum[];
  cards?: CardModelCard[];
  user?: AdminDtoUser;
}
