/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */
import type { AlbumDtoCreateAlbumCardRequest } from './albumDtoCreateAlbumCardRequest';

export interface AlbumDtoCreateAlbumRequest {
  cards?: AlbumDtoCreateAlbumCardRequest[];
  title?: string;
}
