/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */
import type { CardModelCard } from './cardModelCard';

export interface AlbumModelAlbum {
  cards?: CardModelCard[];
  created_at?: number;
  id?: string;
  title?: string;
  total_cards?: number;
}
