/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */

export interface AlbumDtoCreateAlbumCardRequest {
  description?: string;
  image_url?: string;
  name?: string;
  number?: string;
}
