/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */

export interface AlbumDtoRegisterCardRequest {
  album_id?: string;
  card_id?: string;
  contact_id?: string;
  secret?: string;
}
