/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */

export interface AlbumParticipantModelAlbumParticipant {
  album_id?: string;
  assigned_card_id?: string;
  joined_at?: number;
  user_id?: string;
}
