/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */

export interface CardModelCard {
  album_id?: string;
  created_at?: number;
  description?: string;
  id?: string;
  image_url?: string;
  name?: string;
  number?: string;
  updated_at?: number;
}
