/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */

export interface SqlcAlbum {
  createdAt?: number;
  id?: string;
  title?: string;
  totalCards?: number;
}
