/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */

export interface UserDtoUpdateUserRequest {
  description?: string;
  email?: string;
  github?: string;
  linkedin?: string;
  name?: string;
  public_contact?: string;
  public_email?: number;
  web?: string;
}
