/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */

export interface UserModelUser {
  created_at?: number;
  description?: string;
  email?: string;
  github?: string;
  id?: string;
  linkedin?: string;
  name?: string;
  update_at?: number;
  web?: string;
}
