/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */
import type {
  AdminDtoAlbum,
  AdminDtoMessage,
  AdminDtoOverview,
  AdminDtoUpdateUserRoleRequest,
  AdminDtoUser,
  CardModelCard
} from '../../models';

import { customFetch } from '.././CustomFetch';

export type getApiV1AdminAlbumsResponse200 = {
  data: AdminDtoAlbum[]
  status: 200
}

export type getApiV1AdminAlbumsResponseSuccess = (getApiV1AdminAlbumsResponse200) & {
  headers: Headers;
};
;

export type getApiV1AdminAlbumsResponse = (getApiV1AdminAlbumsResponseSuccess)

export const getGetApiV1AdminAlbumsUrl = () => {




  return `/api/v1/admin/albums`
}

/**
 * List all albums with stats
 */
export const getApiV1AdminAlbums = async ( options?: RequestInit): Promise<getApiV1AdminAlbumsResponse> => {

  return customFetch<getApiV1AdminAlbumsResponse>(getGetApiV1AdminAlbumsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type deleteApiV1AdminAlbumsIdResponse200 = {
  data: AdminDtoMessage
  status: 200
}

export type deleteApiV1AdminAlbumsIdResponseSuccess = (deleteApiV1AdminAlbumsIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiV1AdminAlbumsIdResponse = (deleteApiV1AdminAlbumsIdResponseSuccess)

export const getDeleteApiV1AdminAlbumsIdUrl = (id: string,) => {




  return `/api/v1/admin/albums/${id}`
}

/**
 * Delete an album
 */
export const deleteApiV1AdminAlbumsId = async (id: string, options?: RequestInit): Promise<deleteApiV1AdminAlbumsIdResponse> => {

  return customFetch<deleteApiV1AdminAlbumsIdResponse>(getDeleteApiV1AdminAlbumsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}


export type getApiV1AdminCardsResponse200 = {
  data: CardModelCard[]
  status: 200
}

export type getApiV1AdminCardsResponseSuccess = (getApiV1AdminCardsResponse200) & {
  headers: Headers;
};
;

export type getApiV1AdminCardsResponse = (getApiV1AdminCardsResponseSuccess)

export const getGetApiV1AdminCardsUrl = () => {




  return `/api/v1/admin/cards`
}

/**
 * List all cards
 */
export const getApiV1AdminCards = async ( options?: RequestInit): Promise<getApiV1AdminCardsResponse> => {

  return customFetch<getApiV1AdminCardsResponse>(getGetApiV1AdminCardsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type deleteApiV1AdminCardsIdResponse200 = {
  data: AdminDtoMessage
  status: 200
}

export type deleteApiV1AdminCardsIdResponseSuccess = (deleteApiV1AdminCardsIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiV1AdminCardsIdResponse = (deleteApiV1AdminCardsIdResponseSuccess)

export const getDeleteApiV1AdminCardsIdUrl = (id: string,) => {




  return `/api/v1/admin/cards/${id}`
}

/**
 * Delete a card
 */
export const deleteApiV1AdminCardsId = async (id: string, options?: RequestInit): Promise<deleteApiV1AdminCardsIdResponse> => {

  return customFetch<deleteApiV1AdminCardsIdResponse>(getDeleteApiV1AdminCardsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}


export type getApiV1AdminOverviewResponse200 = {
  data: AdminDtoOverview
  status: 200
}

export type getApiV1AdminOverviewResponseSuccess = (getApiV1AdminOverviewResponse200) & {
  headers: Headers;
};
;

export type getApiV1AdminOverviewResponse = (getApiV1AdminOverviewResponseSuccess)

export const getGetApiV1AdminOverviewUrl = () => {




  return `/api/v1/admin/overview`
}

/**
 * Get platform overview metrics
 */
export const getApiV1AdminOverview = async ( options?: RequestInit): Promise<getApiV1AdminOverviewResponse> => {

  return customFetch<getApiV1AdminOverviewResponse>(getGetApiV1AdminOverviewUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type getApiV1AdminUsersResponse200 = {
  data: AdminDtoUser[]
  status: 200
}

export type getApiV1AdminUsersResponseSuccess = (getApiV1AdminUsersResponse200) & {
  headers: Headers;
};
;

export type getApiV1AdminUsersResponse = (getApiV1AdminUsersResponseSuccess)

export const getGetApiV1AdminUsersUrl = () => {




  return `/api/v1/admin/users`
}

/**
 * List all users
 */
export const getApiV1AdminUsers = async ( options?: RequestInit): Promise<getApiV1AdminUsersResponse> => {

  return customFetch<getApiV1AdminUsersResponse>(getGetApiV1AdminUsersUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type putApiV1AdminUsersIdRoleResponse200 = {
  data: AdminDtoUser
  status: 200
}

export type putApiV1AdminUsersIdRoleResponseSuccess = (putApiV1AdminUsersIdRoleResponse200) & {
  headers: Headers;
};
;

export type putApiV1AdminUsersIdRoleResponse = (putApiV1AdminUsersIdRoleResponseSuccess)

export const getPutApiV1AdminUsersIdRoleUrl = (id: string,) => {




  return `/api/v1/admin/users/${id}/role`
}

/**
 * Update user admin role
 */
export const putApiV1AdminUsersIdRole = async (id: string,
    adminDtoUpdateUserRoleRequest: AdminDtoUpdateUserRoleRequest, options?: RequestInit): Promise<putApiV1AdminUsersIdRoleResponse> => {

  return customFetch<putApiV1AdminUsersIdRoleResponse>(getPutApiV1AdminUsersIdRoleUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(adminDtoUpdateUserRoleRequest)
  }
);}


