/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */
import type {
  AdminDtoAlbum,
  AdminDtoCreateCardRequest,
  AdminDtoMessage,
  AdminDtoOverview,
  AdminDtoUpdateAlbumRequest,
  AdminDtoUpdateCardRequest,
  AdminDtoUpdateUserRoleRequest,
  AdminDtoUser,
  AdminDtoUserDetail,
  AlbumDtoCreateAlbumRequest,
  AlbumModelAlbum,
  CardModelCard,
  GetApiV1AdminUsersParams
} from '../../models';

import { customFetch } from '.././CustomFetch';

export type getApiV1AdminAlbumsResponse200 = {
  data: AdminDtoAlbum[]
  status: 200
}

export type getApiV1AdminAlbumsResponseSuccess = (getApiV1AdminAlbumsResponse200) & {
  headers: Headers;
};
;

export type getApiV1AdminAlbumsResponse = (getApiV1AdminAlbumsResponseSuccess)

export const getGetApiV1AdminAlbumsUrl = () => {




  return `/api/v1/admin/albums`
}

/**
 * List all albums with stats
 */
export const getApiV1AdminAlbums = async ( options?: RequestInit): Promise<getApiV1AdminAlbumsResponse> => {

  return customFetch<getApiV1AdminAlbumsResponse>(getGetApiV1AdminAlbumsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type postApiV1AdminAlbumsResponse200 = {
  data: AlbumModelAlbum
  status: 200
}

export type postApiV1AdminAlbumsResponseSuccess = (postApiV1AdminAlbumsResponse200) & {
  headers: Headers;
};
;

export type postApiV1AdminAlbumsResponse = (postApiV1AdminAlbumsResponseSuccess)

export const getPostApiV1AdminAlbumsUrl = () => {




  return `/api/v1/admin/albums`
}

/**
 * Create an album with its cards
 */
export const postApiV1AdminAlbums = async (albumDtoCreateAlbumRequest: AlbumDtoCreateAlbumRequest, options?: RequestInit): Promise<postApiV1AdminAlbumsResponse> => {

  return customFetch<postApiV1AdminAlbumsResponse>(getPostApiV1AdminAlbumsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(albumDtoCreateAlbumRequest)
  }
);}


export type deleteApiV1AdminAlbumsIdResponse200 = {
  data: AdminDtoMessage
  status: 200
}

export type deleteApiV1AdminAlbumsIdResponseSuccess = (deleteApiV1AdminAlbumsIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiV1AdminAlbumsIdResponse = (deleteApiV1AdminAlbumsIdResponseSuccess)

export const getDeleteApiV1AdminAlbumsIdUrl = (id: string,) => {




  return `/api/v1/admin/albums/${id}`
}

/**
 * Delete an album
 */
export const deleteApiV1AdminAlbumsId = async (id: string, options?: RequestInit): Promise<deleteApiV1AdminAlbumsIdResponse> => {

  return customFetch<deleteApiV1AdminAlbumsIdResponse>(getDeleteApiV1AdminAlbumsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}


export type putApiV1AdminAlbumsIdResponse200 = {
  data: AdminDtoAlbum
  status: 200
}

export type putApiV1AdminAlbumsIdResponseSuccess = (putApiV1AdminAlbumsIdResponse200) & {
  headers: Headers;
};
;

export type putApiV1AdminAlbumsIdResponse = (putApiV1AdminAlbumsIdResponseSuccess)

export const getPutApiV1AdminAlbumsIdUrl = (id: string,) => {




  return `/api/v1/admin/albums/${id}`
}

/**
 * Update album title
 */
export const putApiV1AdminAlbumsId = async (id: string,
    adminDtoUpdateAlbumRequest: AdminDtoUpdateAlbumRequest, options?: RequestInit): Promise<putApiV1AdminAlbumsIdResponse> => {

  return customFetch<putApiV1AdminAlbumsIdResponse>(getPutApiV1AdminAlbumsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(adminDtoUpdateAlbumRequest)
  }
);}


export type getApiV1AdminCardsResponse200 = {
  data: CardModelCard[]
  status: 200
}

export type getApiV1AdminCardsResponseSuccess = (getApiV1AdminCardsResponse200) & {
  headers: Headers;
};
;

export type getApiV1AdminCardsResponse = (getApiV1AdminCardsResponseSuccess)

export const getGetApiV1AdminCardsUrl = () => {




  return `/api/v1/admin/cards`
}

/**
 * List all cards
 */
export const getApiV1AdminCards = async ( options?: RequestInit): Promise<getApiV1AdminCardsResponse> => {

  return customFetch<getApiV1AdminCardsResponse>(getGetApiV1AdminCardsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type postApiV1AdminCardsResponse200 = {
  data: CardModelCard
  status: 200
}

export type postApiV1AdminCardsResponseSuccess = (postApiV1AdminCardsResponse200) & {
  headers: Headers;
};
;

export type postApiV1AdminCardsResponse = (postApiV1AdminCardsResponseSuccess)

export const getPostApiV1AdminCardsUrl = () => {




  return `/api/v1/admin/cards`
}

/**
 * Create a card in an album
 */
export const postApiV1AdminCards = async (adminDtoCreateCardRequest: AdminDtoCreateCardRequest, options?: RequestInit): Promise<postApiV1AdminCardsResponse> => {

  return customFetch<postApiV1AdminCardsResponse>(getPostApiV1AdminCardsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(adminDtoCreateCardRequest)
  }
);}


export type deleteApiV1AdminCardsIdResponse200 = {
  data: AdminDtoMessage
  status: 200
}

export type deleteApiV1AdminCardsIdResponseSuccess = (deleteApiV1AdminCardsIdResponse200) & {
  headers: Headers;
};
;

export type deleteApiV1AdminCardsIdResponse = (deleteApiV1AdminCardsIdResponseSuccess)

export const getDeleteApiV1AdminCardsIdUrl = (id: string,) => {




  return `/api/v1/admin/cards/${id}`
}

/**
 * Delete a card
 */
export const deleteApiV1AdminCardsId = async (id: string, options?: RequestInit): Promise<deleteApiV1AdminCardsIdResponse> => {

  return customFetch<deleteApiV1AdminCardsIdResponse>(getDeleteApiV1AdminCardsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}


export type putApiV1AdminCardsIdResponse200 = {
  data: CardModelCard
  status: 200
}

export type putApiV1AdminCardsIdResponseSuccess = (putApiV1AdminCardsIdResponse200) & {
  headers: Headers;
};
;

export type putApiV1AdminCardsIdResponse = (putApiV1AdminCardsIdResponseSuccess)

export const getPutApiV1AdminCardsIdUrl = (id: string,) => {




  return `/api/v1/admin/cards/${id}`
}

/**
 * Update a card
 */
export const putApiV1AdminCardsId = async (id: string,
    adminDtoUpdateCardRequest: AdminDtoUpdateCardRequest, options?: RequestInit): Promise<putApiV1AdminCardsIdResponse> => {

  return customFetch<putApiV1AdminCardsIdResponse>(getPutApiV1AdminCardsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(adminDtoUpdateCardRequest)
  }
);}


export type getApiV1AdminOverviewResponse200 = {
  data: AdminDtoOverview
  status: 200
}

export type getApiV1AdminOverviewResponseSuccess = (getApiV1AdminOverviewResponse200) & {
  headers: Headers;
};
;

export type getApiV1AdminOverviewResponse = (getApiV1AdminOverviewResponseSuccess)

export const getGetApiV1AdminOverviewUrl = () => {




  return `/api/v1/admin/overview`
}

/**
 * Get platform overview metrics
 */
export const getApiV1AdminOverview = async ( options?: RequestInit): Promise<getApiV1AdminOverviewResponse> => {

  return customFetch<getApiV1AdminOverviewResponse>(getGetApiV1AdminOverviewUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type getApiV1AdminUsersResponse200 = {
  data: AdminDtoUser[]
  status: 200
}

export type getApiV1AdminUsersResponseSuccess = (getApiV1AdminUsersResponse200) & {
  headers: Headers;
};
;

export type getApiV1AdminUsersResponse = (getApiV1AdminUsersResponseSuccess)

export const getGetApiV1AdminUsersUrl = (params?: GetApiV1AdminUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/users?${stringifiedParams}` : `/api/v1/admin/users`
}

/**
 * List users, optionally filtered by email
 */
export const getApiV1AdminUsers = async (params?: GetApiV1AdminUsersParams, options?: RequestInit): Promise<getApiV1AdminUsersResponse> => {

  return customFetch<getApiV1AdminUsersResponse>(getGetApiV1AdminUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}


export type getApiV1AdminUsersIdResponse200 = {
  data: AdminDtoUserDetail
  status: 200
}

export type getApiV1AdminUsersIdResponseSuccess = (getApiV1AdminUsersIdResponse200) & {
  headers: Headers;
};
;

export type getApiV1AdminUsersIdResponse = (getApiV1AdminUsersIdResponseSuccess)

export const getGetApiV1AdminUsersIdUrl = (id: string,) => {




  return `/api/v1/admin/users/${id}`
}

/**
 * Get user detail with albums and cards
 */
export const getApiV1AdminUsersId = async (id: string, options?: RequestInit): Promise<getApiV1AdminUsersIdResponse> => {

  return customFetch<getApiV1AdminUsersIdResponse>(getGetApiV1AdminUsersIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}


export type putApiV1AdminUsersIdRoleResponse200 = {
  data: AdminDtoUser
  status: 200
}

export type putApiV1AdminUsersIdRoleResponseSuccess = (putApiV1AdminUsersIdRoleResponse200) & {
  headers: Headers;
};
;

export type putApiV1AdminUsersIdRoleResponse = (putApiV1AdminUsersIdRoleResponseSuccess)

export const getPutApiV1AdminUsersIdRoleUrl = (id: string,) => {




  return `/api/v1/admin/users/${id}/role`
}

/**
 * Update user admin role
 */
export const putApiV1AdminUsersIdRole = async (id: string,
    adminDtoUpdateUserRoleRequest: AdminDtoUpdateUserRoleRequest, options?: RequestInit): Promise<putApiV1AdminUsersIdRoleResponse> => {

  return customFetch<putApiV1AdminUsersIdRoleResponse>(getPutApiV1AdminUsersIdRoleUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(adminDtoUpdateUserRoleRequest)
  }
);}


