/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */
import type {
  ContactDtoContact
} from '../../models';

import { customFetch } from '.././CustomFetch';

export type getApiV1ContactResponse200 = {
  data: ContactDtoContact[]
  status: 200
}

export type getApiV1ContactResponseSuccess = (getApiV1ContactResponse200) & {
  headers: Headers;
};
;

export type getApiV1ContactResponse = (getApiV1ContactResponseSuccess)

export const getGetApiV1ContactUrl = () => {




  return `/api/v1/contact`
}

/**
 * List contacts of the current user
 */
export const getApiV1Contact = async ( options?: RequestInit): Promise<getApiV1ContactResponse> => {

  return customFetch<getApiV1ContactResponse>(getGetApiV1ContactUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


