/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */
import type {
  CardDtoCreateCardRequest,
  CardModelCard
} from '../../models';

import { customFetch } from '.././CustomFetch';

export type postApiV1CardResponse200 = {
  data: CardModelCard
  status: 200
}

export type postApiV1CardResponseSuccess = (postApiV1CardResponse200) & {
  headers: Headers;
};
;

export type postApiV1CardResponse = (postApiV1CardResponseSuccess)

export const getPostApiV1CardUrl = () => {




  return `/api/v1/card`
}

/**
 * Create card
 */
export const postApiV1Card = async (cardDtoCreateCardRequest: CardDtoCreateCardRequest, options?: RequestInit): Promise<postApiV1CardResponse> => {

  return customFetch<postApiV1CardResponse>(getPostApiV1CardUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(cardDtoCreateCardRequest)
  }
);}


