// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"
)

const getOverviewStats = `-- name: GetOverviewStats :one
SELECT
    (SELECT COUNT(*) FROM album) AS albums,
    (SELECT COUNT(*) FROM user) AS users,
    (SELECT COUNT(*) FROM card) AS cards,
    (SELECT COUNT(*) FROM album_participant) AS participants,
    (SELECT COUNT(*) FROM contact) AS contacts,
    (SELECT COUNT(*) FROM user_card_collection) AS collected
`

type GetOverviewStatsRow struct {
	Albums       int64
	Users        int64
	Cards        int64
	Participants int64
	Contacts     int64
	Collected    int64
}

func (q *Queries) GetOverviewStats(ctx context.Context) (GetOverviewStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getOverviewStats)
	var i GetOverviewStatsRow
	err := row.Scan(
		&i.Albums,
		&i.Users,
		&i.Cards,
		&i.Participants,
		&i.Contacts,
		&i.Collected,
	)
	return i, err
}
