// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: album.sql

package sqlc

import (
	"context"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO album (
  id, title, total_cards, created_at
) VALUES (
  ?, ?, ?, ?
) RETURNING id, title, total_cards, created_at
`

type CreateAlbumParams struct {
	ID         string
	Title      string
	TotalCards int64
	CreatedAt  int64
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRowContext(ctx, createAlbum,
		arg.ID,
		arg.Title,
		arg.TotalCards,
		arg.CreatedAt,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TotalCards,
		&i.CreatedAt,
	)
	return i, err
}

const getAlbum = `-- name: GetAlbum :one
SELECT id, title, total_cards, created_at FROM album
WHERE id = ? LIMIT 1
`

func (q *Queries) GetAlbum(ctx context.Context, id string) (Album, error) {
	row := q.db.QueryRowContext(ctx, getAlbum, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TotalCards,
		&i.CreatedAt,
	)
	return i, err
}

const listAlbums = `-- name: ListAlbums :many
SELECT id, title, total_cards, created_at FROM album
ORDER BY created_at
`

func (q *Queries) ListAlbums(ctx context.Context) ([]Album, error) {
	rows, err := q.db.QueryContext(ctx, listAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TotalCards,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByUserId = `-- name: ListAlbumsByUserId :many
SELECT a.id, a.title, a.total_cards, a.created_at
FROM album_participant ap
JOIN album a ON ap.album_id = a.id
WHERE ap.user_id = ?
ORDER BY ap.joined_at DESC
`

func (q *Queries) ListAlbumsByUserId(ctx context.Context, userID string) ([]Album, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TotalCards,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbum = `-- name: UpdateAlbum :one
UPDATE album
SET title = ?,
total_cards = ?
WHERE id = ?
RETURNING id, title, total_cards, created_at
`

type UpdateAlbumParams struct {
	Title      string
	TotalCards int64
	ID         string
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (Album, error) {
	row := q.db.QueryRowContext(ctx, updateAlbum, arg.Title, arg.TotalCards, arg.ID)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TotalCards,
		&i.CreatedAt,
	)
	return i, err
}
