// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: album_participant.sql

package sqlc

import (
	"context"
)

const createAlbumParticipant = `-- name: CreateAlbumParticipant :one
INSERT INTO album_participant (
  album_id, user_id, assigned_card_id, joined_at, secret
) VALUES (
  ?, ?, ?, ?, ?
) RETURNING album_id, user_id, assigned_card_id, joined_at, secret
`

type CreateAlbumParticipantParams struct {
	AlbumID        string
	UserID         string
	AssignedCardID string
	JoinedAt       int64
	Secret         string
}

func (q *Queries) CreateAlbumParticipant(ctx context.Context, arg CreateAlbumParticipantParams) (AlbumParticipant, error) {
	row := q.db.QueryRowContext(ctx, createAlbumParticipant,
		arg.AlbumID,
		arg.UserID,
		arg.AssignedCardID,
		arg.JoinedAt,
		arg.Secret,
	)
	var i AlbumParticipant
	err := row.Scan(
		&i.AlbumID,
		&i.UserID,
		&i.AssignedCardID,
		&i.JoinedAt,
		&i.Secret,
	)
	return i, err
}

const deleteAlbumParticipantsByAlbumId = `-- name: DeleteAlbumParticipantsByAlbumId :exec
DELETE FROM album_participant
WHERE album_id = ?
`

func (q *Queries) DeleteAlbumParticipantsByAlbumId(ctx context.Context, albumID string) error {
	_, err := q.db.ExecContext(ctx, deleteAlbumParticipantsByAlbumId, albumID)
	return err
}

const getAlbumParticipant = `-- name: GetAlbumParticipant :one
SELECT album_id, user_id, assigned_card_id, joined_at, secret FROM album_participant
WHERE album_id = ? AND user_id = ? LIMIT 1
`

type GetAlbumParticipantParams struct {
	AlbumID string
	UserID  string
}

func (q *Queries) GetAlbumParticipant(ctx context.Context, arg GetAlbumParticipantParams) (AlbumParticipant, error) {
	row := q.db.QueryRowContext(ctx, getAlbumParticipant, arg.AlbumID, arg.UserID)
	var i AlbumParticipant
	err := row.Scan(
		&i.AlbumID,
		&i.UserID,
		&i.AssignedCardID,
		&i.JoinedAt,
		&i.Secret,
	)
	return i, err
}

const getCardByAlbumParticipant = `-- name: GetCardByAlbumParticipant :one
SELECT c.id, c.album_id, c.number, c.name, c.description, c.image_url, c.created_at, c.updated_at
FROM album_participant ap
JOIN card c ON ap.assigned_card_id = c.id
WHERE ap.album_id = ?
  AND ap.assigned_card_id = ?
  AND ap.user_id = ?
`

type GetCardByAlbumParticipantParams struct {
	AlbumID        string
	AssignedCardID string
	UserID         string
}

func (q *Queries) GetCardByAlbumParticipant(ctx context.Context, arg GetCardByAlbumParticipantParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardByAlbumParticipant, arg.AlbumID, arg.AssignedCardID, arg.UserID)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlbumParticipants = `-- name: ListAlbumParticipants :many
SELECT album_id, user_id, assigned_card_id, joined_at, secret FROM album_participant
ORDER BY created_at
`

func (q *Queries) ListAlbumParticipants(ctx context.Context) ([]AlbumParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumParticipants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlbumParticipant
	for rows.Next() {
		var i AlbumParticipant
		if err := rows.Scan(
			&i.AlbumID,
			&i.UserID,
			&i.AssignedCardID,
			&i.JoinedAt,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbumParticipantSecret = `-- name: UpdateAlbumParticipantSecret :one
UPDATE album_participant
SET secret = ?
WHERE album_id = ? AND user_id = ?
RETURNING album_id, user_id, assigned_card_id, joined_at, secret
`

type UpdateAlbumParticipantSecretParams struct {
	Secret  string
	AlbumID string
	UserID  string
}

func (q *Queries) UpdateAlbumParticipantSecret(ctx context.Context, arg UpdateAlbumParticipantSecretParams) (AlbumParticipant, error) {
	row := q.db.QueryRowContext(ctx, updateAlbumParticipantSecret, arg.Secret, arg.AlbumID, arg.UserID)
	var i AlbumParticipant
	err := row.Scan(
		&i.AlbumID,
		&i.UserID,
		&i.AssignedCardID,
		&i.JoinedAt,
		&i.Secret,
	)
	return i, err
}
