// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: card.sql

package sqlc

import (
	"context"
)

const createCard = `-- name: CreateCard :one
INSERT INTO card (
  id, album_id, number, name, description, image_url, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, album_id, number, name, description, image_url, created_at, updated_at
`

type CreateCardParams struct {
	ID          string
	AlbumID     string
	Number      string
	Name        string
	Description string
	ImageUrl    string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, createCard,
		arg.ID,
		arg.AlbumID,
		arg.Number,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM card
WHERE id = ?
`

func (q *Queries) DeleteCard(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCard, id)
	return err
}

const deleteCardsByAlbumId = `-- name: DeleteCardsByAlbumId :exec
DELETE FROM card
WHERE album_id = ?
`

func (q *Queries) DeleteCardsByAlbumId(ctx context.Context, albumID string) error {
	_, err := q.db.ExecContext(ctx, deleteCardsByAlbumId, albumID)
	return err
}

const getCard = `-- name: GetCard :one
SELECT id, album_id, number, name, description, image_url, created_at, updated_at FROM card
WHERE id = ? LIMIT 1
`

func (q *Queries) GetCard(ctx context.Context, id string) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCard, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCards = `-- name: ListCards :many
SELECT id, album_id, number, name, description, image_url, created_at, updated_at FROM card
ORDER BY number
`

func (q *Queries) ListCards(ctx context.Context) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsByAlbumId = `-- name: ListCardsByAlbumId :many
SELECT id, album_id, number, name, description, image_url, created_at, updated_at FROM card
WHERE album_id = ?
ORDER BY number
`

func (q *Queries) ListCardsByAlbumId(ctx context.Context, albumID string) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listCardsByAlbumId, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :one
UPDATE card
SET album_id = ?,
    number = ?,
    name = ?,
    description = ?,
    image_url = ?,
    updated_at = ?
WHERE id = ?
RETURNING id, album_id, number, name, description, image_url, created_at, updated_at
`

type UpdateCardParams struct {
	AlbumID     string
	Number      string
	Name        string
	Description string
	ImageUrl    string
	UpdatedAt   int64
	ID          string
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, updateCard,
		arg.AlbumID,
		arg.Number,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.AlbumID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
