// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: card_pool.sql

package sqlc

import (
	"context"
)

const createCardPoolRow = `-- name: CreateCardPoolRow :one
INSERT INTO card_pool(
    album_id, card_id
) VALUES (
    ?, ?
) RETURNING album_id, card_id, is_drawn
`

type CreateCardPoolRowParams struct {
	AlbumID string
	CardID  string
}

func (q *Queries) CreateCardPoolRow(ctx context.Context, arg CreateCardPoolRowParams) (CardPool, error) {
	row := q.db.QueryRowContext(ctx, createCardPoolRow, arg.AlbumID, arg.CardID)
	var i CardPool
	err := row.Scan(&i.AlbumID, &i.CardID, &i.IsDrawn)
	return i, err
}

const deleteCardPoolByAlbumId = `-- name: DeleteCardPoolByAlbumId :exec
DELETE FROM card_pool
WHERE album_id = ?
`

func (q *Queries) DeleteCardPoolByAlbumId(ctx context.Context, albumID string) error {
	_, err := q.db.ExecContext(ctx, deleteCardPoolByAlbumId, albumID)
	return err
}

const getRandomAvailableCard = `-- name: GetRandomAvailableCard :one
SELECT card_id 
FROM card_pool 
WHERE album_id = ? AND is_drawn = 0 
ORDER BY RANDOM() 
LIMIT 1
`

func (q *Queries) GetRandomAvailableCard(ctx context.Context, albumID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRandomAvailableCard, albumID)
	var card_id string
	err := row.Scan(&card_id)
	return card_id, err
}

const markCardAsDrawn = `-- name: MarkCardAsDrawn :one
UPDATE card_pool 
SET is_drawn = 1 
WHERE album_id = ? AND card_id = ?
RETURNING album_id, card_id, is_drawn
`

type MarkCardAsDrawnParams struct {
	AlbumID string
	CardID  string
}

func (q *Queries) MarkCardAsDrawn(ctx context.Context, arg MarkCardAsDrawnParams) (CardPool, error) {
	row := q.db.QueryRowContext(ctx, markCardAsDrawn, arg.AlbumID, arg.CardID)
	var i CardPool
	err := row.Scan(&i.AlbumID, &i.CardID, &i.IsDrawn)
	return i, err
}

const resetCardPool = `-- name: ResetCardPool :one
UPDATE card_pool 
SET is_drawn = 0 
WHERE album_id = ?
RETURNING album_id, card_id, is_drawn
`

func (q *Queries) ResetCardPool(ctx context.Context, albumID string) (CardPool, error) {
	row := q.db.QueryRowContext(ctx, resetCardPool, albumID)
	var i CardPool
	err := row.Scan(&i.AlbumID, &i.CardID, &i.IsDrawn)
	return i, err
}
