// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact.sql

package sqlc

import (
	"context"
)

const createContact = `-- name: CreateContact :one
INSERT OR IGNORE INTO contact (
    user_id, met_user_id, scanned_at
) VALUES (
    ?, ? ,?
) RETURNING user_id, met_user_id, scanned_at
`

type CreateContactParams struct {
	UserID    string
	MetUserID string
	ScannedAt int64
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, createContact, arg.UserID, arg.MetUserID, arg.ScannedAt)
	var i Contact
	err := row.Scan(&i.UserID, &i.MetUserID, &i.ScannedAt)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT u.id, u.name, u.email, u.github, u.linkedin, u.web, u.description,
       u.is_admin, u.picture, u.created_at, u.updated_at, c.scanned_at
FROM contact c
JOIN user u ON u.id = c.met_user_id
WHERE c.user_id = ?
ORDER BY c.scanned_at DESC
`

type ListContactsRow struct {
	ID          string
	Name        string
	Email       string
	Github      string
	Linkedin    string
	Web         string
	Description string
	IsAdmin     int64
	Picture     string
	CreatedAt   int64
	UpdatedAt   int64
	ScannedAt   int64
}

func (q *Queries) ListContacts(ctx context.Context, userID string) ([]ListContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContacts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsRow
	for rows.Next() {
		var i ListContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Github,
			&i.Linkedin,
			&i.Web,
			&i.Description,
			&i.IsAdmin,
			&i.Picture,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
