// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact.sql

package sqlc

import (
	"context"
)

const createContact = `-- name: CreateContact :one
INSERT OR IGNORE INTO contact (
    user_id, met_user_id, scanned_at
) VALUES (
    ?, ? ,?
) RETURNING user_id, met_user_id, scanned_at
`

type CreateContactParams struct {
	UserID    string
	MetUserID string
	ScannedAt int64
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, createContact, arg.UserID, arg.MetUserID, arg.ScannedAt)
	var i Contact
	err := row.Scan(&i.UserID, &i.MetUserID, &i.ScannedAt)
	return i, err
}
