// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type Album struct {
	ID         string
	Title      string
	TotalCards int64
	CreatedAt  int64
}

type AlbumParticipant struct {
	AlbumID        string
	UserID         string
	AssignedCardID string
	JoinedAt       int64
	Secret         string
}

type Card struct {
	ID          string
	AlbumID     string
	Number      string
	Name        string
	Description string
	ImageUrl    string
	CreatedAt   int64
	UpdatedAt   int64
}

type CardPool struct {
	AlbumID string
	CardID  string
	IsDrawn int64
}

type Contact struct {
	UserID    string
	MetUserID string
	ScannedAt int64
}

type SchemaMigration struct {
	Version string
}

type User struct {
	ID          string
	Name        string
	Email       string
	Github      string
	Linkedin    string
	Web         string
	Description string
	IsAdmin     int64
	CreatedAt   int64
	UpdatedAt   int64
}

type UserCardCollection struct {
	UserID     string
	AlbumID    string
	CardID     string
	UnlockedAt int64
}
