// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO user (
  id, name, email, github, linkedin, web, description, is_admin, picture, created_at, updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) ON CONFLICT(email) DO UPDATE SET
    updated_at = excluded.updated_at,
    picture = excluded.picture
RETURNING id, name, email, github, linkedin, web, description, is_admin, picture, created_at, updated_at
`

type CreateUserParams struct {
	ID          string
	Name        string
	Email       string
	Github      string
	Linkedin    string
	Web         string
	Description string
	IsAdmin     int64
	Picture     string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Github,
		arg.Linkedin,
		arg.Web,
		arg.Description,
		arg.IsAdmin,
		arg.Picture,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Github,
		&i.Linkedin,
		&i.Web,
		&i.Description,
		&i.IsAdmin,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, github, linkedin, web, description, is_admin, picture, created_at, updated_at FROM user
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Github,
		&i.Linkedin,
		&i.Web,
		&i.Description,
		&i.IsAdmin,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, github, linkedin, web, description, is_admin, picture, created_at, updated_at FROM user
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Github,
		&i.Linkedin,
		&i.Web,
		&i.Description,
		&i.IsAdmin,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, github, linkedin, web, description, is_admin, picture, created_at, updated_at FROM user
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Github,
			&i.Linkedin,
			&i.Web,
			&i.Description,
			&i.IsAdmin,
			&i.Picture,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByEmail = `-- name: SearchUsersByEmail :many
SELECT id, name, email, github, linkedin, web, description, is_admin, picture, created_at, updated_at FROM user
WHERE email LIKE ?
ORDER BY name
`

func (q *Queries) SearchUsersByEmail(ctx context.Context, email string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsersByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Github,
			&i.Linkedin,
			&i.Web,
			&i.Description,
			&i.IsAdmin,
			&i.Picture,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE user
SET name = ?,
email = ?,
github = ?,
linkedin = ?,
web = ?,
description = ?,
updated_at = ?
WHERE id = ?
RETURNING id, name, email, github, linkedin, web, description, is_admin, picture, created_at, updated_at
`

type UpdateUserParams struct {
	Name        string
	Email       string
	Github      string
	Linkedin    string
	Web         string
	Description string
	UpdatedAt   int64
	ID          string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Github,
		arg.Linkedin,
		arg.Web,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Github,
		&i.Linkedin,
		&i.Web,
		&i.Description,
		&i.IsAdmin,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserIsAdmin = `-- name: UpdateUserIsAdmin :one
UPDATE user
SET is_admin = ?,
updated_at = ?
WHERE id = ?
RETURNING id, name, email, github, linkedin, web, description, is_admin, picture, created_at, updated_at
`

type UpdateUserIsAdminParams struct {
	IsAdmin   int64
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateUserIsAdmin(ctx context.Context, arg UpdateUserIsAdminParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserIsAdmin, arg.IsAdmin, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Github,
		&i.Linkedin,
		&i.Web,
		&i.Description,
		&i.IsAdmin,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
