// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_card_collection.sql

package sqlc

import (
	"context"
)

const cardInCollection = `-- name: CardInCollection :one
SELECT EXISTS(
    SELECT 1 FROM user_card_collection
    WHERE user_id = ? AND album_id = ? AND card_id = ?
) AS owned
`

type CardInCollectionParams struct {
	UserID  string
	AlbumID string
	CardID  string
}

func (q *Queries) CardInCollection(ctx context.Context, arg CardInCollectionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, cardInCollection, arg.UserID, arg.AlbumID, arg.CardID)
	var owned bool
	err := row.Scan(&owned)
	return owned, err
}

const collectCard = `-- name: CollectCard :exec
INSERT OR IGNORE INTO user_card_collection (user_id, album_id, card_id, unlocked_at)
VALUES (?, ?, ?, ?)
`

type CollectCardParams struct {
	UserID     string
	AlbumID    string
	CardID     string
	UnlockedAt int64
}

func (q *Queries) CollectCard(ctx context.Context, arg CollectCardParams) error {
	_, err := q.db.ExecContext(ctx, collectCard,
		arg.UserID,
		arg.AlbumID,
		arg.CardID,
		arg.UnlockedAt,
	)
	return err
}

const getUserCollection = `-- name: GetUserCollection :many
SELECT c.id, c.album_id, c.number, c.name, c.description, c.image_url, c.created_at, c.updated_at
FROM user_card_collection ucc
JOIN card c ON ucc.card_id = c.id
WHERE ucc.user_id = ? AND ucc.album_id = ?
ORDER BY c.number
`

type GetUserCollectionParams struct {
	UserID  string
	AlbumID string
}

func (q *Queries) GetUserCollection(ctx context.Context, arg GetUserCollectionParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getUserCollection, arg.UserID, arg.AlbumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.AlbumID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
