/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */
import type {
  UserDtoUpdateUserRequest,
  UserModelUser
} from '../../models';

import { customFetch } from '.././CustomFetch';

export type putApiV1UserIdResponse200 = {
  data: UserModelUser
  status: 200
}

export type putApiV1UserIdResponseSuccess = (putApiV1UserIdResponse200) & {
  headers: Headers;
};
;

export type putApiV1UserIdResponse = (putApiV1UserIdResponseSuccess)

export const getPutApiV1UserIdUrl = (id: string,) => {




  return `/api/v1/user/${id}`
}

/**
 * Update user by ID
 */
export const putApiV1UserId = async (id: string,
    userDtoUpdateUserRequest: UserDtoUpdateUserRequest, options?: RequestInit): Promise<putApiV1UserIdResponse> => {

  return customFetch<putApiV1UserIdResponse>(getPutApiV1UserIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userDtoUpdateUserRequest)
  }
);}


