/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */
import type {
  AlbumParticipantDtoCreateAlbumParticipantRequest,
  AlbumParticipantModelAlbumParticipant
} from '../../models';

import { customFetch } from '.././CustomFetch';

export type postApiV1AlbumParticipantResponse200 = {
  data: AlbumParticipantModelAlbumParticipant
  status: 200
}

export type postApiV1AlbumParticipantResponseSuccess = (postApiV1AlbumParticipantResponse200) & {
  headers: Headers;
};
;

export type postApiV1AlbumParticipantResponse = (postApiV1AlbumParticipantResponseSuccess)

export const getPostApiV1AlbumParticipantUrl = () => {




  return `/api/v1/album_participant`
}

/**
 * Create Album participant
 */
export const postApiV1AlbumParticipant = async (albumParticipantDtoCreateAlbumParticipantRequest: AlbumParticipantDtoCreateAlbumParticipantRequest, options?: RequestInit): Promise<postApiV1AlbumParticipantResponse> => {

  return customFetch<postApiV1AlbumParticipantResponse>(getPostApiV1AlbumParticipantUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(albumParticipantDtoCreateAlbumParticipantRequest)
  }
);}


