/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */
import type {
  UserModelUser
} from '../../models';

import { customFetch } from '.././CustomFetch';

export type getApiV1AuthMeResponse200 = {
  data: UserModelUser
  status: 200
}

export type getApiV1AuthMeResponseSuccess = (getApiV1AuthMeResponse200) & {
  headers: Headers;
};
;

export type getApiV1AuthMeResponse = (getApiV1AuthMeResponseSuccess)

export const getGetApiV1AuthMeUrl = () => {




  return `/api/v1/auth/me`
}

/**
 * Get current session user
 */
export const getApiV1AuthMe = async ( options?: RequestInit): Promise<getApiV1AuthMeResponse> => {

  return customFetch<getApiV1AuthMeResponse>(getGetApiV1AuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


