/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Trading Card Album API
 * MVP para intercambio de tarjetas coleccionables.
 * OpenAPI spec version: 1.0
 */
import type {
  AlbumDtoCreateAlbumRequest,
  AlbumDtoRegisterCardRequest,
  AlbumModelAlbum,
  AlbumParticipantDtoShareAssignedCardResponse,
  CardModelCard,
  GetApiV1AlbumIdShareAssignedCardParams,
  SqlcAlbum
} from '../../models';

import { customFetch } from '.././CustomFetch';

export type getApiV1AlbumResponse200 = {
  data: SqlcAlbum[]
  status: 200
}

export type getApiV1AlbumResponseSuccess = (getApiV1AlbumResponse200) & {
  headers: Headers;
};
;

export type getApiV1AlbumResponse = (getApiV1AlbumResponseSuccess)

export const getGetApiV1AlbumUrl = () => {




  return `/api/v1/album`
}

/**
 * Get albums by user
 */
export const getApiV1Album = async ( options?: RequestInit): Promise<getApiV1AlbumResponse> => {

  return customFetch<getApiV1AlbumResponse>(getGetApiV1AlbumUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


export type postApiV1AlbumResponse200 = {
  data: AlbumModelAlbum
  status: 200
}

export type postApiV1AlbumResponseSuccess = (postApiV1AlbumResponse200) & {
  headers: Headers;
};
;

export type postApiV1AlbumResponse = (postApiV1AlbumResponseSuccess)

export const getPostApiV1AlbumUrl = () => {




  return `/api/v1/album`
}

/**
 * Create album
 */
export const postApiV1Album = async (albumDtoCreateAlbumRequest: AlbumDtoCreateAlbumRequest, options?: RequestInit): Promise<postApiV1AlbumResponse> => {

  return customFetch<postApiV1AlbumResponse>(getPostApiV1AlbumUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(albumDtoCreateAlbumRequest)
  }
);}


export type getApiV1AlbumIdResponse200 = {
  data: AlbumModelAlbum
  status: 200
}

export type getApiV1AlbumIdResponseSuccess = (getApiV1AlbumIdResponse200) & {
  headers: Headers;
};
;

export type getApiV1AlbumIdResponse = (getApiV1AlbumIdResponseSuccess)

export const getGetApiV1AlbumIdUrl = (id: string,) => {




  return `/api/v1/album/${id}`
}

/**
 * Get album by id
 */
export const getApiV1AlbumId = async (id: string, options?: RequestInit): Promise<getApiV1AlbumIdResponse> => {

  return customFetch<getApiV1AlbumIdResponse>(getGetApiV1AlbumIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}


export type getApiV1AlbumIdAssignedCardResponse200 = {
  data: CardModelCard
  status: 200
}

export type getApiV1AlbumIdAssignedCardResponseSuccess = (getApiV1AlbumIdAssignedCardResponse200) & {
  headers: Headers;
};
;

export type getApiV1AlbumIdAssignedCardResponse = (getApiV1AlbumIdAssignedCardResponseSuccess)

export const getGetApiV1AlbumIdAssignedCardUrl = (id: string,) => {




  return `/api/v1/album/${id}/assigned_card`
}

/**
 * Assigned card
 */
export const getApiV1AlbumIdAssignedCard = async (id: string, options?: RequestInit): Promise<getApiV1AlbumIdAssignedCardResponse> => {

  return customFetch<getApiV1AlbumIdAssignedCardResponse>(getGetApiV1AlbumIdAssignedCardUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}


export type getApiV1AlbumIdCardResponse200 = {
  data: CardModelCard[]
  status: 200
}

export type getApiV1AlbumIdCardResponseSuccess = (getApiV1AlbumIdCardResponse200) & {
  headers: Headers;
};
;

export type getApiV1AlbumIdCardResponse = (getApiV1AlbumIdCardResponseSuccess)

export const getGetApiV1AlbumIdCardUrl = (id: string,) => {




  return `/api/v1/album/${id}/card`
}

/**
 * Card Pool
 */
export const getApiV1AlbumIdCard = async (id: string, options?: RequestInit): Promise<getApiV1AlbumIdCardResponse> => {

  return customFetch<getApiV1AlbumIdCardResponse>(getGetApiV1AlbumIdCardUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}


export type getApiV1AlbumIdShareAssignedCardResponse200ApplicationJson = {
  data: AlbumParticipantDtoShareAssignedCardResponse
  status: 200
}

export type getApiV1AlbumIdShareAssignedCardResponse200ImagePng = {
  data: Blob
  status: 200
}

export type getApiV1AlbumIdShareAssignedCardResponseSuccess = (getApiV1AlbumIdShareAssignedCardResponse200ApplicationJson | getApiV1AlbumIdShareAssignedCardResponse200ImagePng) & {
  headers: Headers;
};
;

export type getApiV1AlbumIdShareAssignedCardResponse = (getApiV1AlbumIdShareAssignedCardResponseSuccess)

export const getGetApiV1AlbumIdShareAssignedCardUrl = (id: string,
    params?: GetApiV1AlbumIdShareAssignedCardParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/album/${id}/share_assigned_card?${stringifiedParams}` : `/api/v1/album/${id}/share_assigned_card`
}

/**
 * Share assigned card
 */
export const getApiV1AlbumIdShareAssignedCard = async (id: string,
    params?: GetApiV1AlbumIdShareAssignedCardParams, options?: RequestInit): Promise<getApiV1AlbumIdShareAssignedCardResponse> => {

  return customFetch<getApiV1AlbumIdShareAssignedCardResponse>(getGetApiV1AlbumIdShareAssignedCardUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}


export type postApiV1AlbumNewCardResponse200 = {
  data: CardModelCard
  status: 200
}

export type postApiV1AlbumNewCardResponseSuccess = (postApiV1AlbumNewCardResponse200) & {
  headers: Headers;
};
;

export type postApiV1AlbumNewCardResponse = (postApiV1AlbumNewCardResponseSuccess)

export const getPostApiV1AlbumNewCardUrl = () => {




  return `/api/v1/album/new_card`
}

/**
 * Register new card
 */
export const postApiV1AlbumNewCard = async (albumDtoRegisterCardRequest: AlbumDtoRegisterCardRequest, options?: RequestInit): Promise<postApiV1AlbumNewCardResponse> => {

  return customFetch<postApiV1AlbumNewCardResponse>(getPostApiV1AlbumNewCardUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(albumDtoRegisterCardRequest)
  }
);}


